function usaProvinceStr(){
	var str="";
	str+='<option value="-1">Please select</option>';
		str+='<option value="Alabama">Alabama</option>';
		str+='<option value="Alaska">Alaska</option>';
		str+='<option value="Arizona">Arizona</option>';
		str+='<option value="Arkansas">Arkansas</option>';
		str+='<option value="Armed Forces Americas">Armed Forces Americas</option>';
		str+='<option value="Armed Forces Europe">Armed Forces Europe</option>';
		str+='<option value="Armed Forces Pacific">Armed Forces Pacific</option>';
		str+='<option value="California">California</option>';
		str+='<option value="Colorado">Colorado</option>';
		str+='<option value="Connecticut">Connecticut</option>';
		str+='<option value="Delaware">Delaware</option>';
		str+='<option value="Dist of Columbia">Dist of Columbia</option>';
		str+='<option value="Florida">Florida</option>';
		str+='<option value="Georgia">Georgia</option>';
		str+='<option value="Guam">Guam</option>';
		str+='<option value="Hawaii">Hawaii</option>';
		str+='<option value="Idaho">Idaho</option>';
		str+='<option value="Illinois">Illinois</option>';
		str+='<option value="Indiana">Indiana</option>';
		str+='<option value="Iowa">Iowa</option>';
		str+='<option value="Kansas">Kansas</option>';
		str+='<option value="Kentucky">Kentucky</option>';
		str+='<option value="Louisiana">Louisiana</option>';
		str+='<option value="Maine">Maine</option>';
		str+='<option value="Maryland">Maryland</option>';
		str+='<option value="Massachusetts">Massachusetts</option>';
		str+='<option value="Michigan">Michigan</option>';
		str+='<option value="Minnesota">Minnesota</option>';
		str+='<option value="Mississippi">Mississippi</option>';
		str+='<option value="Missouri">Missouri</option>';
		str+='<option value="Montana">Montana</option>';
		str+='<option value="Nebraska">Nebraska</option>';
		str+='<option value="Nevada">Nevada</option>';
		str+='<option value="New Hampshire">New Hampshire</option>';
		str+='<option value="New Jersey">New Jersey</option>';
		str+='<option value="New Mexico">New Mexico</option>';
		str+='<option value="New York">New York</option>';
		str+='<option value="North Carolina">North Carolina</option>';
		str+='<option value="North Dakota">North Dakota</option>';
		str+='<option value="Ohio">Ohio</option>';
		str+='<option value="Oklahoma">Oklahoma</option>';
		str+='<option value="Oregon">Oregon</option>';
		str+='<option value="Pennsylvania">Pennsylvania</option>';
		str+='<option value="Puerto Rico">Puerto Rico</option>';
		str+='<option value="Rhode Island">Rhode Island</option>';
		str+='<option value="South Carolina">South Carolina</option>';
		str+='<option value="South Dakota">South Dakota</option>';
		str+='<option value="Tennessee">Tennessee</option>';
		str+='<option value="Texas">Texas</option>';
		str+='<option value="Utah">Utah</option>';
		str+='<option value="Vermont">Vermont</option>';
		str+='<option value="Virgin Islands">Virgin Islands</option>';
		str+='<option value="Virginia">Virginia</option>';
		str+='<option value="Washington">Washington</option>';
		str+='<option value="West Virginia">West Virginia</option>';
		str+='<option value="Wisconsin">Wisconsin</option>';
		str+='<option value="Wyoming">Wyoming</option>';
	
	return str;
}